name: go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: go test -race -coverprofile=coverage.out ./...
      - run: cd zapimpl && go test -race ./...
      - run: cd logrusimpl && go test -race ./...
      - run: cd zerologimpl && go test -race ./...
      - run: cd stdlogimpl && go test -race ./...
      - uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          files: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
